HappyGrapher/config/routes.rb
Rails.application.routes.draw do
  resources :statistics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'statistics#index'


end

HappyGrapher/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

HappyGrapher/app/models/competition.rb
class Competition < ApplicationRecord
end

HappyGrapher/app/models/competition_result.rb
class CompetitionResult < ApplicationRecord
  belongs_to :sporter
  belongs_to :competition
end

HappyGrapher/app/models/country.rb
class Country < ApplicationRecord
end

HappyGrapher/app/models/sporter.rb
class Sporter < ApplicationRecord
  belongs_to :country
end

HappyGrapher/app/models/statistic.rb
class Statistic < ApplicationRecord
end

HappyGrapher/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

HappyGrapher/app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :set_statistic, only: [:show, :edit, :update, :destroy]

  # GET /statistics
  # GET /statistics.json
  def index
    # @statistics = Statistic.all
    @sporters = Sporter.all
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
  end

  # GET /statistics/new
  def new
    @statistic = Statistic.new
  end

  # GET /statistics/1/edit
  def edit
  end

  # POST /statistics
  # POST /statistics.json
  def create
    @statistic = Statistic.new(statistic_params)

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to @statistic, notice: 'Statistic was successfully created.' }
        format.json { render :show, status: :created, location: @statistic }
      else
        format.html { render :new }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statistics/1
  # PATCH/PUT /statistics/1.json
  def update
    respond_to do |format|
      if @statistic.update(statistic_params)
        format.html { redirect_to @statistic, notice: 'Statistic was successfully updated.' }
        format.json { render :show, status: :ok, location: @statistic }
      else
        format.html { render :edit }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic.destroy
    respond_to do |format|
      format.html { redirect_to statistics_url, notice: 'Statistic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statistic
      @statistic = Statistic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def statistic_params
      params.fetch(:statistic, {})
    end
end

HappyGrapher/app/helpers/application_helper.rb
module ApplicationHelper
end

HappyGrapher/app/helpers/statistics_helper.rb
module StatisticsHelper

  def sporters_by_age
    bar_chart @sporters.group(:age).count, height: '500px', library: {
      title: {text: 'Sporters by age', x:-20},
      yAxis: {
        allowDecimals: false,
        title: {
          text: 'Ages count'
        }
      },
      xAxis: {
        title: {
          text: 'Age'
        }
      }
    }
  end

end

HappyGrapher/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HappyGrapher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

HappyGrapher/app/views/statistics/_form.html.erb
<%= form_for(statistic) do |f| %>
  <% if statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(statistic.errors.count, "error") %> prohibited this statistic from being saved:</h2>

      <ul>
      <% statistic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HappyGrapher/app/views/statistics/edit.html.erb
<h1>Editing Statistic</h1>

<%= render 'form', statistic: @statistic %>

<%= link_to 'Show', @statistic %> |
<%= link_to 'Back', statistics_path %>

HappyGrapher/app/views/statistics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statistics</h1>
<%= bar_chart @sporters.group(:age).count %>


<hr />
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>



<br>

HappyGrapher/app/views/statistics/new.html.erb
<h1>New Statistic</h1>

<%= render 'form', statistic: @statistic %>

<%= link_to 'Back', statistics_path %>

HappyGrapher/app/views/statistics/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_statistic_path(@statistic) %> |
<%= link_to 'Back', statistics_path %>